# Generated by Django 4.2.3 on 2023-07-15 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='image',
            new_name='recipe_image',
        ),
    ]
