# Generated by Django 4.2.3 on 2023-07-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0005_recipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='view_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
