# Generated by Django 4.2.3 on 2023-07-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0009_reportcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcard',
            name='date_of_reportcard_generation',
            field=models.DateField(auto_now_add=True),
        ),
    ]
