# Generated by Django 4.2.3 on 2023-07-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0010_alter_reportcard_date_of_reportcard_generation'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
