# Generated by Django 4.2.3 on 2023-07-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
